# Generated by Django 5.2.15 on 2026-06-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_created_at_job_description_job_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
    ]
