# Generated by Django 5.2.15 on 2026-06-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_application_applied_at_application_resume_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Applied', max_length=30),
        ),
    ]
