# Generated by Django 5.2.15 on 2026-07-03 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_application_updated_at_alter_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
            options={
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
