# Generated by Django 5.2.15 on 2026-07-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_application_ats_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer',
        ),
        migrations.AlterField(
            model_name='application',
            name='ats_score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], db_index=True, default='Applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employer', 'Employer'), ('candidate', 'Candidate')], db_index=True, max_length=20),
        ),
    ]
