# Generated by Django 5.2.15 on 2026-07-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_job_employer_alter_application_ats_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_call_status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Queued', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='call_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate_available',
            field=models.BooleanField(default=True),
        ),
    ]
