# Generated by Django 5.2.15 on 2026-07-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_aiinterviewsession_aiquestion_aianswer_calllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Introduction', 'Introduction'), ('Experience', 'Experience'), ('Skills', 'Skills'), ('Availability', 'Availability'), ('Salary', 'Salary')], max_length=30)),
                ('question', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobQuestionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mappings', to='core.job')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questiontemplate')),
            ],
        ),
    ]
