# Generated by Django 5.2.15 on 2026-07-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_questiontemplate_jobquestionmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aianswer',
            old_name='answered_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='aianswer',
            name='completeness_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='final_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='keyword_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='relevance_score',
            field=models.FloatField(default=0),
        ),
    ]
