# Generated by Django 5.2.15 on 2026-07-23 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_availabilityslot_interviewschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interviewschedule')),
            ],
        ),
    ]
