from django.urls import path

from .views import (
    TestAPIView,
    SignupAPIView,
    LogoutAPIView,
    JobListAPIView,
    JobCreateAPIView,
    CandidateAPIView,
    AdminAPIView,
    ApplyJobAPIView,
    CandidateProfileAPIView,
    EmployerProfileAPIView,
    ResumeUploadAPIView,
    UserListAPIView,
    JobUpdateAPIView,
    JobStatusAPIView,
    LatestJobAPIView,
    FeaturedJobAPIView,
    ApplicationHistoryAPIView,
    ApplicationStatusAPIView,
    EmployerJobListAPIView,
    ApplicantListAPIView,
    EmployerDashboardAPIView,
    SaveJobAPIView,
    SavedJobListAPIView,
    RecommendedJobAPIView,
    ApplicationTimelineAPIView,
    ApproveEmployerAPIView,
    BlockUserAPIView,
    AdminJobListAPIView,
    DeleteJobAPIView,
    AdminJobUpdateAPIView,
    AdminPlatformStatsAPIView,
    AdminAuditLogAPIView,
    UnblockUserAPIView,
    ResumeParserAPIView,
    ParsedResumeAPIView,
    ATSScoreAPIView,
    RankedCandidateAPIView,
    AutoHiringAPIView,
    EmployerOverrideAPIView,
    AutoNotificationAPIView,
    BatchAutoHiringAPIView
)
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [

    path('test/', TestAPIView.as_view()),

    path('signup/', SignupAPIView.as_view()),

    path(
        'login/',
        TokenObtainPairView.as_view()
    ),

    path(
        'refresh/',
        TokenRefreshView.as_view()
    ),

    path(
        'logout/',
        LogoutAPIView.as_view()
    ),

    path(
        'jobs/',
        JobListAPIView.as_view()
    ),

    path(
        'jobs/create/',
        JobCreateAPIView.as_view()
    ),
    
    path(
    'candidate/',
    CandidateAPIView.as_view()
   ),

path(
    'admin-dashboard/',
    AdminAPIView.as_view()
   ),


path(
    'candidate/profile/',
    CandidateProfileAPIView.as_view()
),

path(
    'employer/profile/',
    EmployerProfileAPIView.as_view()
),
path(
    'candidate/upload-resume/',
    ResumeUploadAPIView.as_view()
),
path(
    'users/',
    UserListAPIView.as_view()
),
path(
    'jobs/<int:job_id>/update/',
    JobUpdateAPIView.as_view()
),

path(
    'jobs/<int:job_id>/status/',
    JobStatusAPIView.as_view()
),
path(
    'jobs/latest/',
    LatestJobAPIView.as_view()
),

path(
    'jobs/featured/',
    FeaturedJobAPIView.as_view()
),
path(
    'jobs/<int:job_id>/apply/',
    ApplyJobAPIView.as_view()
),
path(
    'applications/',
    ApplicationHistoryAPIView.as_view()
),
path(
    'applications/<int:application_id>/status/',
    ApplicationStatusAPIView.as_view()
),
path(
    'employer/jobs/',
    EmployerJobListAPIView.as_view()
),
path(
    'jobs/<int:job_id>/applicants/',
     ApplicantListAPIView.as_view()
),
path(
    'employer/dashboard/',
    EmployerDashboardAPIView.as_view()
),
path(
    'jobs/<int:job_id>/save/',
    SaveJobAPIView.as_view()
),
path(
    'candidate/saved-jobs/',
    SavedJobListAPIView.as_view()
),
path(
    'candidate/recommended-jobs/',
    RecommendedJobAPIView.as_view()
),
path(
    'applications/<int:application_id>/timeline/',
    ApplicationTimelineAPIView.as_view()
),
path(
    'api/admin/employers/<int:employer_id>/approve/',
    ApproveEmployerAPIView.as_view()
),
path(
    'api/admin/users/<int:user_id>/block/',
    BlockUserAPIView.as_view()
),
path(
    'api/admin/users/<int:user_id>/unblock/',
    UnblockUserAPIView.as_view()
),
path(
    'api/admin/jobs/',
    AdminJobListAPIView.as_view()
),
path(
    'api/admin/jobs/<int:job_id>/delete/',
    DeleteJobAPIView.as_view()
),
path(
    'api/admin/jobs/<int:job_id>/update/',
    AdminJobUpdateAPIView.as_view()
),
path(
    'api/admin/platform-stats/',
    AdminPlatformStatsAPIView.as_view()
),
path(
    'api/admin/audit-logs/',
    AdminAuditLogAPIView.as_view()
),
path(
    "candidate/parse-resume/",
    ResumeParserAPIView.as_view()
),
path(
    'candidate/resume-parsed/',
    ParsedResumeAPIView.as_view()
),
path(
    "applications/<int:application_id>/ats-score/",
    ATSScoreAPIView.as_view()
),
path(
    "jobs/<int:job_id>/ranked-candidates/",
    RankedCandidateAPIView.as_view()
),
path(
    "applications/<int:application_id>/auto-hiring/",
    AutoHiringAPIView.as_view()
),
path(
    "applications/<int:application_id>/override/",
    EmployerOverrideAPIView.as_view()
),
path(
    "applications/<int:application_id>/notify/",
    AutoNotificationAPIView.as_view()
),
path(
    "jobs/<int:job_id>/batch-auto-hiring/",
    BatchAutoHiringAPIView.as_view()
),
]