name: Zecpath CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Django check
        env:
          SECRET_KEY: test-secret-key
          DEBUG: "True"
          RAZORPAY_KEY_ID: test-key
          RAZORPAY_KEY_SECRET: test-secret
          EMAIL_HOST_USER: test@example.com
          EMAIL_HOST_PASSWORD: test-password
        run: python manage.py check

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/zecpath_project
            git pull origin main
            source venv313/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart zecpath
            sudo systemctl reload nginx